import { StyleSheet } from "react-native";


export const styles = StyleSheet.create({
    imageContainer: {
        width: 150,
        height: 150,
        borderRadius: 12,
        overflow: 'hidden',
        backgroundColor: '#f8f9fa',
        
    },
     itemCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        margin: 8,
        marginBottom: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
        overflow: 'hidden',
        

      },
    itemInfo: {
        flex: 1,
        justifyContent: 'space-between',
        padding: 16,
    },
    itemHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 8,
    },
    itemName: {
        fontSize: 16,
        fontWeight: '600',
        color: '#2c3e50',
        flex: 1,
        lineHeight: 20,
    },

    itemDetails: {
        gap: 8,
    },
    detailRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 4,
    },
    detailBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f8f9fa',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
        flex: 1,
        marginHorizontal: 2,
    },
    detailCode: {
        fontSize: 12,
        color: '#6c757d',
        fontWeight: '500',
        marginLeft: 4,
    },
    detailType: {
        fontSize: 12,
        color: '#6c757d',
        fontWeight: '500',
        marginLeft: 4,
    },
    barcodeRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    barcodeText: {
        fontSize: 12,
        color: '#6c757d',
        marginLeft: 6,
        flex: 1,
        fontFamily: 'monospace',
    },
    priceRow: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f0f9ff',
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 8,
        marginBottom: 6,
        borderLeftWidth: 3,
        borderLeftColor: '#0ea5e9',
    },
    priceContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    priceText: {
        fontSize: 14,
        color: '#0c4a6e',
        fontWeight: '600',
        fontFamily: 'monospace',
    },
    priceLabel: {
        fontSize: 11,
        color: '#0369a1',
        fontWeight: '500',
        marginRight: 8,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    priceIcon: {
        marginRight: 6,
    },
    availabilityBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
        alignSelf: 'flex-start',
    },
    availabilityText: {
        fontSize: 12,
        fontWeight: '600',
        marginLeft: 4,
    },
    actionButtonsContainer: {
        flexDirection: 'row',
        paddingHorizontal: 16,
        paddingBottom: 16,
        paddingTop: 8,
        gap: 12,
    },
    actionButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 12,
        backgroundColor: '#4f46e5',
        shadowColor: '#4f46e5',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
        elevation: 4,
        borderWidth: 0,
    },
    infoButton: {
        backgroundColor: '#8b93d1',
        borderWidth: 1,
        borderColor: '#9ca3db',
        shadowColor: '#8b93d1',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
        transform: [{ scale: 1 }],
    },
    actionButtonText: {
        fontSize: 14,
        fontWeight: '700',
        color: '#ffffff',
        marginLeft: 8,
        letterSpacing: 0.5,
    },
    stockButtonText: {
        color: '#ffffff',
        fontWeight: '700',
    },

    stockButton: {
        backgroundColor: '#6b9080',
        borderWidth: 1,
        borderColor: '#7ba590',
        shadowColor: '#6b9080',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
        transform: [{ scale: 1 }],
      },

      SearchItemCardcontainer: {
        backgroundColor: '#ffffff',
        borderRadius: 12,
        marginHorizontal: 16,
        marginVertical: 6,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
        overflow: 'hidden',
    },
    SearchItemCardcontent: {
        flexDirection: 'row',
        padding: 16,
        alignItems: 'center',
    },
    SearchItemCardimageContainer: {
        marginRight: 16,
    },
    SearchItemCardimage: {
        width: 64,
        height: 64,
        borderRadius: 8,
        backgroundColor: '#f8f9fa',
    },
    SearchItemCardimagePlaceholder: {
        width: 64,
        height: 64,
        borderRadius: 8,
        backgroundColor: '#f8f9fa',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#e9ecef',
        borderStyle: 'dashed',
    },
    SearchItemCardinfo: {
        flex: 1,
    },
    SearchItemCardheader: {
        marginBottom: 8,
    },
    SearchItemCardname: {
        fontSize: 16,
        fontWeight: '600',
        color: '#2c3e50',
        lineHeight: 20,
    },
    SearchItemCarddetails: {
        gap: 6,
    },
    SearchItemCarddetailRow: {
        flexDirection: 'row',
        gap: 8,
    },
    SearchItemCardcodeBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f8f9fa',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 8,
        flex: 1,
    },
    SearchItemCardcodeText: {
        fontSize: 12,
        color: '#6c757d',
        fontWeight: '500',
        marginLeft: 4,
    },
    SearchItemCardtypeBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f0f9ff',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 8,
        flex: 1,
    },
    SearchItemCardtypeText: {
        fontSize: 12,
        color: '#0369a1',
        fontWeight: '500',
        marginLeft: 4,
    },
    SearchItemCardbarcodeRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    SearchItemCardbarcodeText: {
        fontSize: 12,
        color: '#6c757d',
        marginLeft: 6,
        fontFamily: 'monospace',
    },
    SearchItemCardpriceContainer: {
        flexDirection: 'row',
        gap: 8,
    },
    SearchItemCardpriceRow: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f0f9ff',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 6,
        borderLeftWidth: 2,
        borderLeftColor: '#0ea5e9',
    },
    SearchItemCardpriceLabel: {
        fontSize: 10,
        color: '#0369a1',
        fontWeight: '500',
        marginRight: 6,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    SearchItemCardpriceText: {
        fontSize: 12,
        color: '#0c4a6e',
        fontWeight: '600',
        fontFamily: 'monospace',
    },
    SearchItemCardboxPriceRow: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f0fdf4',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 6,
        borderLeftWidth: 2,
        borderLeftColor: '#22c55e',
    },
    SearchItemCardboxPriceLabel: {
        fontSize: 10,
        color: '#166534',
        fontWeight: '500',
        marginRight: 6,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    SearchItemCardboxPriceText: {
        fontSize: 12,
        color: '#14532d',
        fontWeight: '600',
        fontFamily: 'monospace',
    },
    SearchItemCardtagsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 4,
        alignItems: 'center',
    },
    SearchItemCardtag: {
        backgroundColor: '#f8f9fa',
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#e9ecef',
    },
    SearchItemCardtagText: {
        color: '#495057',
        fontSize: 11,
        fontWeight: '500',
    },
    SearchItemCardmoreTagsText: {
        fontSize: 11,
        color: '#94a3b8',
        fontWeight: '500',
        fontStyle: 'italic',
    },
    SearchItemCardchevronContainer: {
        marginLeft: 12,
        justifyContent: 'center',
    },
})