import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#f5f7fa',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 16,
      backgroundColor: '#fff',
      borderBottomWidth: 1,
      borderBottomColor: '#e0e0e0',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    backButton: {
      marginRight: 16,
    },
    headerTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#2c3e50',
      letterSpacing: 0.5,
    },
    filterSection: {
      backgroundColor: '#fff',
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: '#e0e0e0',
    },
    filterLabel: {
      fontSize: 14,
      color: '#7f8c8d',
      marginBottom: 8,
    },
    chipsContainer: {
      flexDirection: 'row',
    },
    chip: {
      paddingHorizontal: 16,
      paddingVertical: 10,
      backgroundColor: '#ecf0f1',
      borderRadius: 25,
      marginRight: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 2,
    },
    selectedChip: {
      backgroundColor: '#3498db',
      shadowColor: '#3498db',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 4,
      transform: [{ scale: 1.05 }],
    },
    chipText: {
      fontSize: 14,
      color: '#34495e',
    },
    selectedChipText: {
      color: '#fff',
    },
    summaryContainer: {
      backgroundColor: '#fff',
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: '#e0e0e0',
    },
    summaryText: {
      fontSize: 16,
      fontWeight: '600',
      color: '#34495e',
    },
    loadingContainer: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    loadingText: {
      marginTop: 12,
      fontSize: 16,
      color: '#7f8c8d',
    },
    errorContainer: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      padding: 20,
    },
    errorTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#e74c3c',
      marginTop: 12,
      marginBottom: 8,
    },
    errorMessage: {
      fontSize: 14,
      color: '#7f8c8d',
      textAlign: 'center',
      marginBottom: 20,
    },
    retryButton: {
      backgroundColor: '#3498db',
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 8,
    },
    retryButtonText: {
      color: '#fff',
      fontSize: 14,
      fontWeight: '600',
    },
    emptyContainer: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      padding: 20,
    },
    emptyTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#2ecc71',
      marginTop: 12,
      marginBottom: 8,
    },
    emptyMessage: {
      fontSize: 14,
      color: '#7f8c8d',
      textAlign: 'center',
    },
    listContainer: {
      padding: 16,
    },
    itemContainer: {
      backgroundColor: '#fff',
      borderRadius: 16,
      marginBottom: 16,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 4,
      },
      shadowOpacity: 0.12,
      shadowRadius: 6,
      elevation: 8,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: 'rgba(0,0,0,0.05)',
    },
    itemContent: {
      flexDirection: 'row',
      padding: 18,
    },
    imageContainer: {
      position: 'relative',
      marginRight: 16,
    },
    itemImage: {
      width: 80,
      height: 80,
      borderRadius: 12,
      backgroundColor: '#f8f9fa',
      borderWidth: 2,
      borderColor: '#e9ecef',
    },
    imagePlaceholder: {
      width: 80,
      height: 80,
      borderRadius: 12,
      backgroundColor: '#f8f9fa',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: '#e9ecef',
      borderStyle: 'dashed',
    },
    urgentOverlay: {
      position: 'absolute',
      top: -8,
      right: -8,
      backgroundColor: '#e74c3c',
      borderRadius: 15,
      width: 30,
      height: 30,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 3,
      borderColor: '#fff',
      shadowColor: '#e74c3c',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.4,
      shadowRadius: 4,
      elevation: 5,
    },
    itemDetails: {
      flex: 1,
      justifyContent: 'space-between',
    },
    itemHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: 8,
    },
    itemName: {
      fontSize: 16,
      fontWeight: '600',
      color: '#2c3e50',
      flex: 1,
      marginRight: 8,
      lineHeight: 22,
    },
    expiryBadge: {
      backgroundColor: '#f39c12',
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 20,
      alignSelf: 'flex-start',
      shadowColor: '#f39c12',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 3,
      elevation: 3,
    },
    criticalBadge: {
      backgroundColor: '#e74c3c',
      shadowColor: '#e74c3c',
    },
    urgentBadge: {
      backgroundColor: '#c0392b',
      shadowColor: '#c0392b',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.4,
      shadowRadius: 5,
      elevation: 5,
      borderWidth: 2,
      borderColor: 'rgba(255,255,255,0.3)',
    },
    expiryText: {
      fontSize: 12,
      color: '#fff',
      fontWeight: '700',
      letterSpacing: 0.3,
    },
    itemInfo: {
      marginBottom: 12,
    },
    infoRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 4,
    },
    itemBarcode: {
      fontSize: 13,
      color: '#6c757d',
      marginLeft: 6,
      fontFamily: 'monospace',
    },
    itemStock: {
      fontSize: 13,
      color: '#6c757d',
      marginLeft: 6,
    },
    tagsContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginTop: 8,
    },
    tag: {
      backgroundColor: '#e3f2fd',
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 16,
      marginRight: 6,
      marginBottom: 4,
      borderWidth: 1,
      borderColor: '#bbdefb',
      shadowColor: '#1976d2',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.15,
      shadowRadius: 2,
      elevation: 2,
    },
    moreTagsIndicator: {
      backgroundColor: '#f5f5f5',
      borderColor: '#e0e0e0',
    },
    tagText: {
      fontSize: 11,
      color: '#1976d2',
      fontWeight: '500',
    },
    pricingSection: {
      backgroundColor: '#f8f9fa',
      borderRadius: 12,
      padding: 14,
      marginVertical: 8,
      borderLeftWidth: 4,
      borderLeftColor: '#2ecc71',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 2,
      borderWidth: 1,
      borderColor: '#e9ecef',
    },
    discountedPrice: {
      fontWeight: '600',
      color: '#e74c3c',
    },
    savingsRow: {
      marginTop: 6,
      paddingTop: 6,
      borderTopWidth: 1,
      borderTopColor: '#dee2e6',
      alignItems: 'center',
    },
    savingsText: {
      fontSize: 12,
      fontWeight: '600',
      color: '#155724',
      textAlign: 'center',
      backgroundColor: '#d4edda',
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: '#c3e6cb',
      shadowColor: '#27ae60',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
      elevation: 2,
    },
  });
  