import { StyleSheet } from "react-native";

export const AddItemScreenStyles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#f8fafc',
    },
    scrollContent: {
      padding: 16,
      paddingBottom: 40,
    },
    headerRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 20,
      paddingHorizontal: 4,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    headerText: {
      fontSize: 28,
      fontWeight: '700',
      marginLeft: 12,
      color: '#1e293b',
      letterSpacing: -0.5,
    },
    formContainer: {
      backgroundColor: '#ffffff',
      borderRadius: 16,
      padding: 20,
      marginBottom: 16,
      shadowColor: '#64748b',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.05,
      shadowRadius: 12,
      elevation: 4,
      borderWidth: 1,
      borderColor: '#f1f5f9',
    },
    sectionTitle: {
      fontSize: 20,
      fontWeight: '700',
      marginTop: 24,
      marginBottom: 16,
      color: '#1e293b',
      letterSpacing: -0.3,
    },
    inputGroup: {
      marginBottom: 20,
    },
    label: {
      fontSize: 15,
      marginBottom: 8,
      color: '#475569',
      fontWeight: '600',
      letterSpacing: 0.2,
    },
    input: {
      backgroundColor: '#f8fafc',
      borderWidth: 2,
      borderColor: '#e2e8f0',
      borderRadius: 12,
      padding: 16,
      fontSize: 16,
      color: '#1e293b',
      fontWeight: '500',
      shadowColor: '#64748b',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    barcodeContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    barcodeInput: {
      flex: 1,
    },
    scanButton: {
      backgroundColor: '#3b82f6',
      paddingHorizontal: 16,
      paddingVertical: 16,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#3b82f6',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 3,
    },
    typeButtonsContainer: {
      flexDirection: 'row',
      gap: 8,
    },
    typeButton: {
      flex: 1,
      backgroundColor: '#f8fafc',
      borderWidth: 2,
      borderColor: '#e2e8f0',
      paddingVertical: 14,
      paddingHorizontal: 12,
      borderRadius: 12,
      alignItems: 'center',
      shadowColor: '#64748b',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    selectedTypeButton: {
      backgroundColor: '#3b82f6',
      borderColor: '#3b82f6',
      shadowColor: '#3b82f6',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 3,
    },
    typeButtonText: {
      fontSize: 14,
      fontWeight: '600',
      color: '#64748b',
      letterSpacing: 0.3,
    },
    selectedTypeButtonText: {
      color: '#ffffff',
      fontWeight: '700',
    },
    switchContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#f8fafc',
      padding: 16,
      borderRadius: 12,
      borderWidth: 2,
      borderColor: '#e2e8f0',
    },
    switchLabel: {
      marginLeft: 12,
      fontSize: 16,
      color: '#475569',
      fontWeight: '600',
    },
    submitButton: {
      backgroundColor: '#10b981',
      borderRadius: 16,
      paddingVertical: 18,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 32,
      shadowColor: '#10b981',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 6,
    },
    disabledButton: {
      backgroundColor: '#94a3b8',
      shadowOpacity: 0.1,
    },
    buttonIcon: {
      marginRight: 8,
    },
    submitButtonText: {
      color: '#ffffff',
      fontSize: 18,
      fontWeight: '700',
      letterSpacing: 0.3,
    },
    
    // Tags styles
    tagsLoading: {
      marginVertical: 12,
    },
    tagsScrollView: {
      maxHeight: 120,
    },
    tagsContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      paddingVertical: 8,
      paddingRight: 16,
    },
    tagButton: {
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 20,
      marginRight: 8,
      marginBottom: 8,
      borderWidth: 2,
      borderColor: '#e2e8f0',
      backgroundColor: '#f8fafc',
      shadowColor: '#64748b',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    selectedTagButton: {
      borderColor: 'transparent',
      shadowColor: 'rgba(59, 130, 246, 0.4)',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 3,
    },
    tagText: {
      fontSize: 14,
      fontWeight: '600',
      color: '#64748b',
      letterSpacing: 0.2,
    },
    selectedTagText: {
      color: '#ffffff',
      fontWeight: '700',
    },
    
    // Recommendations Section
    recommendationsSection: {
      marginBottom: 20,
      backgroundColor: '#f8fafc',
      borderRadius: 16,
      borderWidth: 2,
      borderColor: '#e2e8f0',
      overflow: 'hidden',
      shadowColor: '#64748b',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    recommendationsHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 16,
      backgroundColor: '#f1f5f9',
      borderBottomWidth: 2,
      borderBottomColor: '#e2e8f0',
    },
    recommendationsTitle: {
      fontSize: 17,
      fontWeight: '700',
      color: '#334155',
      letterSpacing: -0.2,
    },
    recommendationsToggle: {
      padding: 4,
    },
    recommendationsContent: {
      padding: 12,
    },
    noRecommendationsText: {
      textAlign: 'center',
      color: '#6c757d',
      padding: 16,
    },
  
    itemImageContainerHorizontal: {
      width: 100,
      height: 100,
      borderRadius: 4,
      overflow: 'hidden',
      backgroundColor: '#f7f9fa',
      marginBottom: 10,
    },
    itemImage: {
      width: '100%',
      height: '100%',
    },
    noImagePlaceholder: {
      width: '100%',
      height: '100%',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#f7f9fa',
    },
    itemName: {
      fontSize: 14,
      fontWeight: 'bold',
      color: '#2c3e50',
      marginBottom: 2,
      textAlign: 'center',
      width: '100%',
    },
    itemCode: {
      fontSize: 12,
      color: '#7f8c8d',
      textAlign: 'center',
      width: '100%',
    },
    itemBarcode: {
      fontSize: 12,
      color: '#7f8c8d',
      textAlign: 'center',
      width: '100%',
      marginBottom: 8,
    },
    selectButtonHorizontal: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: '#2ecc71',
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 4,
    },
    loadingMoreContainer: {
      width: 60,
      height: 180,
      justifyContent: 'center',
      alignItems: 'center',
      marginHorizontal: 8,
    },
    
    // Image section styles
    imagePreviewContainer: {
      backgroundColor: '#f8fafc',
      borderRadius: 16,
      padding: 16,
      marginTop: 16,
      marginBottom: 12,
      borderWidth: 2,
      borderColor: '#e2e8f0',
      shadowColor: '#64748b',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    imagePreview: {
      width: '100%',
      height: 220,
      borderRadius: 12,
      backgroundColor: '#ffffff',
      marginBottom: 12,
      borderWidth: 1,
      borderColor: '#e2e8f0',
    },
    imageInfo: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    imageInfoText: {
      fontSize: 13,
      color: '#64748b',
      flex: 1,
      fontWeight: '500',
    },
    removeImageButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 8,
      backgroundColor: '#fef2f2',
      borderWidth: 1,
      borderColor: '#fecaca',
    },
    removeImageText: {
      fontSize: 13,
      color: '#dc2626',
      marginLeft: 6,
      fontWeight: '600',
    },
    imageActionsContainer: {
      flexDirection: 'row',
      gap: 12,
    },
    imageActionButton: {
      flex: 1,
      backgroundColor: '#3b82f6',
      borderRadius: 12,
      paddingVertical: 16,
      paddingHorizontal: 16,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#3b82f6',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.2,
      shadowRadius: 6,
      elevation: 4,
    },
    imageActionText: {
      color: '#ffffff',
      fontSize: 16,
      fontWeight: '700',
      marginLeft: 8,
      letterSpacing: 0.2,
    },
    urlInputButton: {
      flex: 1,
      backgroundColor: '#f8fafc',
      borderRadius: 12,
      paddingVertical: 16,
      paddingHorizontal: 16,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: '#e2e8f0',
      shadowColor: '#64748b',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    urlInputText: {
      color: '#475569',
      fontSize: 16,
      fontWeight: '600',
      marginLeft: 8,
      letterSpacing: 0.2,
    },
    
    // AI Analysis Button styles
    aiAnalysisButton: {
      backgroundColor: '#8b5cf6',
      borderRadius: 16,
      paddingVertical: 16,
      paddingHorizontal: 20,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 16,
      shadowColor: '#8b5cf6',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 6,
      borderWidth: 2,
      borderColor: 'transparent',
    },
    aiAnalysisCompleteButton: {
      backgroundColor: '#10b981',
      shadowColor: '#10b981',
    },
    aiAnalysisButtonText: {
      color: '#ffffff',
      fontSize: 17,
      fontWeight: '700',
      marginLeft: 10,
      letterSpacing: 0.3,
    },
  });
  